""" These are dictionaries that allow Volume2Record objects to parse .V2 files """
# This file is referenced by the class file.

# CSMIP CGS Volume 2 Text Header.
# Dictionary with field mapping to line number and character range
# Example: txthdrinfo[0] = (1<--line number, 1<--beginning character, 80<--end character,
#                           'txt_vol2title'<-- key used in the 'info' dictionary for Volume2Record class,
#                           'Title'<--description according to the 1985 DMG CSMIP document (standard tape format)

v2th = [
    (1, 1, 80, 'txt_vol2title', 'Title'),
    (2, 1, 80, 'txt_vol1title', 'Volume 1 Title'),
    (3, -1, 29, 'txt_eqname', 'Earthquake Name'),
    (4, 1, 40, 'txt_eqdatetimelocal', 'Earthquake date, time (local time)'),
    (4, 41, 80, 'txt_eqorigintimegmt', 'Earthquake origin time (GMT)'),
    (5, 1, 24, 'txt_accidnum', 'Accelogram identification number'),
    (5, 36, 77, 'txt_tgtimegmt', 'Trigger time (GMT), if available'),
    (6, 13, 17, 'txt_stnnum', 'Station number'),
    (6, 21, 27, 'txt_stnlat', 'Station latitude'),
    (6, 30, 37, 'txt_stnlon', 'Station longitude'),
    (6, 40, 47, 'txt_insttype', 'Instrument type (SMA, RFT, CRA, etc.)'),
    (6, 54, 57, 'txt_instserial', 'Instrument serial number'),
    (6, 60, 61, 'txt_numchnacc', 'Number of channels on accelograph (non-triaxial)'),
    (6, 71, 72, 'txt_totchnstn', 'Total number of channels at station'),
    (7, -1, 30, 'txt_stnname', 'Station name'),
    (8, 6, 7, 'txt_accchnnumcomp', 'Accelerogram channel number of this component'),
    (8, 10, 14, 'txt_orient', 'Orientation (0-360 clock from N if horizontal, else "UP" or "DOWN"'),
    (8, 29, 30, 'txt_stnchnnum', 'Station channel number, if multi-instrument station'),
    (8, 47, 80, 'txt_sensorlocdesc', 'Description of sensor location in structure, when appropriate'),
    (9, -1, 31, 'txt_eqtiltline', 'Earthquake tilt line, including name and date'),
    (10, 1, 45, 'txt_eqhypoinfo', 'Earthquake hypocenter information'),
    (10, 46, 80, 'txt_eqmag', 'Earthquake magnitude (ML or other)'),
    (11, 15, 21, 'txt_transnatper', 'Transducer natural period (seconds)'),
    (11, 39, 43, 'txt_damp', 'Damping (fraction of critical)'),
    (11, 60, 64, 'txt_sens', 'Sensitivity'),
    (11, 66, 72, 'txt_sensunits', 'Sensitivity units (typically cm/g)'),
    (12, 40, 46, 'txt_lenv2record', 'Length in seconds on Vol. 2 digitized record'),
    (13, 51, 55, 'txt_peakaccv1', 'Vol. 1 peak acceleration (g)'),
    (13, 64, 60, 'txt_timepeakacc', 'Time of peak acceleration (seconds after triggering)'),
    (14, 31, 36, 'txt_rmsaccv1', 'RMS of Vol. 1 acceleration (g)'),
    (15, 1, 80, 'txt_bandpassfqlim', 'Frequency limits used in the band-pass filtering'),
    (16, 1, 6, 'txt_numptsv2', 'Number of Vol. 2 acceleration, velocity and displacement points'),
    (17, 1, 45, 'txt_timestepv2', 'Time step of Vol. 2 data (equally-spaced)'),
    (18, 1, 64, 'txt_peakaccv2timeval',
     'Value and time of Vol. 2 peak acceleration (time, in seconds after triggering)'),
    (19, 1, 64, 'txt_peakveltimeval', 'Value and time of peak velocity'),
    (20, 1, 64, 'txt_peakdistimeval', 'Value and time of peak displacement'),
    (21, 1, 78, 'txt_initveldis', 'Initial velocity and displacement (computed during processing)'),
    (22, 1, 80, 'txt_eqname2', 'Earthquake name (same as line 9, or line 8 of Vol. 1 header)'),
    (24, 1, 80, 'txt_titline', 'Tilting line used for plot tilting'),
]

# CSMIP CGS Volume 2 Integer header. In the V2 files, it is 100 elements with 16 elements per line
# (field number, line number, start position, endposition, key, description)
v2ih = [
    (1, 26, 1, 5, 'int_accchnnum', 'Accelogram channel number'),
    (3, 26, 11, 15, 'int_stnchnnum', 'Station channel number (same as element 1 if only one instrument at the station'),
    (4, 26, 16, 20, 'int_numchnacc', 'Number of channels on accelerogram'),
    (5, 26, 21, 25, 'int_totchnstn', 'Total number of channels at the station'),
    (7, 26, 31, 35, 'int_shocknum', 'Shock number (1 unless more than one earthquake per trigger'),
    (8, 26, 36, 40, 'int_blank3', '1, indicating that a direct-copy negative was digitized medium'),
    (27, 27, 51, 55, 'int_orient',
     'Orientation of sensor for this channel (0-360 clock from N if horizontal, 500=Up, 600=Down for vertical'),
    (28, 27, 56, 60, 'int_numaccpts', 'Number of digitized acceleration data points'),
    (29, 27, 61, 65, 'int_numleteqname', 'Number of letters in earthquake name (line 3 of text header)'),
    (30, 27, 66, 70, 'int_numletstname', 'Number of letters in station name (line 7 of text header)'),
    (31, 27, 71, 75, 'int_numleteqtitl', 'Number of letters in earthquake title line (line 9 of text header)'),
    (32, 27, 76, 80, 'int_azmrefnorth',
     'Azimuth of reference North of the structure, clockwise from true Northl 0, for a free-field accelerogram'),
    (51, 29, 11, 15, 'int_numaccpts1', 'Number of digitized acceleration data points part 1/2'),
    (52, 29, 16, 20, 'int_numaccpts2', 'Number of digitized acceleration data points part 2/2'),
    (53, 29, 21, 25, 'int_numv2accdpts', 'Number of Vol. 2 acceleration data points'),
    (54, 29, 26, 30, 'int_firstdec', 'First decimation factor in processing (typically 4)'),
    (55, 29, 31, 35, 'int_longdec', 'Decimation factor for long-period filtering of accelerations (typically 10)'),
    (56, 29, 36, 40, 'int_halflenfiltop', 'Half-length of filter operator in BAS'),
    (59, 29, 51, 55, 'int_numleteqtitl2', 'Number of letters in earthquake title'),
    (60, 29, 56, 60, 'int_numletplotname', 'Number of letters for plotting station name'),
    (61, 29, 61, 65, 'int_longdecvel', 'Decimation factor for long-period filtering of velocity (typically 10)'),
    (62, 29, 66, 70, 'int_longdecdis', 'Decimation factor for long-period filtering of displacement (typically 10)'),
    (64, 29, 76, 80, 'int_numvelpts', 'Number of velocity points'),
    (66, 30, 6, 10, 'int_numdispts', 'Number of displacement points')
]

# CSMIP CGS Volume 2 Real header. In the V2 file, it is 100 elements with 8 per line
# (field number, line number, start position, end position, key, description)
v2rh = [
    (1, 33, 1, 10, 'dbl_transnatper', 'Natural period of transducer (seconds)'),
    (2, 33, 11, 20, 'dbl_transdamp', 'Damping of transducer (fraction of critical'),
    (3, 33, 21, 30, 'dbl_lenrecord', 'Length of digitized record (seconds)'),
    (4, 33, 31, 40, 'dbl_rmsrecord', 'RMS value of digitized record (g)'),
    (5, 33, 41, 50, 'dbl_unitrecord', 'Units of digitized acceleration in file (fractions of g, typically 0.10)'),
    (6, 33, 51, 60, 'dbl_transsensitivity', 'Sensitivity of transducer (cm/g)'),
    (7, 33, 61, 70, 'dbl_peakaccv1', 'Peak acceleration (Vol. 1) for this component (g)'),
    (8, 33, 71, 80, 'dbl_timepeakacc', 'Time of peak acceleration value (seconds after trigger)'),
    (9, 34, 1, 10, 'dbl_transnatfqhz', 'Natural frequency of transducer (Hz)'),
    (10, 34, 11, 20, 'dbl_digystepmicrons', 'Digitizer y-step (acceleration) size, in microns (cm/10000)'),
    (11, 34, 21, 30, 'dbl_digystepmillig', 'Digitizer y-step size, in milli-g'),
    (12, 34, 31, 40, 'dbl_digxstepmicrons', 'Digitizer x-step (time) size, in microns (cm/100000)'),
    (13, 34, 41, 50, 'dbl_avgdt', 'Actual average time step, in milliseconds'),
    (14, 34, 51, 60, 'dbl_stddt', 'Standard deviation of time step, in milliseconds'),
    (15, 34, 61, 70, 'dbl_mindt', 'Minimum time step size, as digitized (milliseconds)'),
    (16, 34, 71, 80, 'dbl_maxdt', 'Maximum time step size, as digitized (milliseconds)'),
    (52, 39, 31, 40, 'dbl_cgstosig', 'Scaling factor for converting acceleration from g/10 to cm/sec/sec (98.0665)'),
    (53, 39, 41, 50, 'dbl_dtinterp', 'Time step of Vol. 2 equally-spaced interpolation (sec)'),
    (54, 39, 51, 60, 'dbl_lenv2acc', 'Length of interpolated Vol. 2 acceleration (secs)'),
    (55, 39, 61, 70, 'dbl_transnatfqrad', 'Natural frequency of transducer (radians/sec)'),
    (58, 40, 11, 20, 'dbl_termfqhifq', 'Terminal frequency of high-frequency filter (Hz)'),
    (59, 40, 21, 30, 'dbl_rolloffhifq', 'Roll-off width of high-frequency filter (Hz)'),
    (60, 40, 31, 40, 'dbl_lenresampv2',
     'Length of Vol. 2 output after resampling to sampling interval given in dtinterp'),
    (61, 40, 41, 50, 'dbl_dtv2out', 'Time step of Vol. 2 output (sec)'),
    (62, 40, 51, 60, 'dbl_rolloffcorfqlong', 'Roll-off corner frequency of long-period filter (Hz)'),
    (63, 40, 61, 70, 'dbl_rollofflong', 'Roll-off width of long-period filter (Hz)'),
    (65, 41, 1, 10, 'dbl_peakaccv2time', 'Time of peak acceleration (Vol. 2), seconds'),
    (66, 41, 11, 20, 'dbl_peakaccv2val', 'Peak acceleration value (Vol. 2), cm/sec/sec'),
    (67, 41, 21, 30, 'dbl_peakveltime', 'Time of peak velocity (sec)'),
    (68, 41, 31, 40, 'dbl_peakvelval', 'Peak velocity (cm/sec)'),
    (69, 41, 41, 50, 'dbl_peakdistime', 'Time of peak displacement (sec)'),
    (70, 41, 51, 60, 'dbl_peakdisval', 'Peak displacement (cm)'),
    (71, 41, 61, 70, 'dbl_initvel', 'Initial velocity value (cm/sec)'),
    (72, 41, 71, 80, 'dbl_rolloffcorfqlong2', 'Roll-off corner frequency of long-period filter (Hz)'),
    (73, 42, 1, 10, 'dbl_rolloffcorhifq', 'Roll-off corner frequency of high-frequency filter (Hz)'),
    (74, 42, 11, 20, 'dbl_dtvel', 'Velocity time-step (sec)'),
    (75, 42, 21, 30, 'dbl_dtdis', 'Displacement time-step (sec)'),
    (76, 42, 31, 40, 'dbl_initdis', 'Initial displacement (cm)')
]

# Might want to add more schemas for CSMIP Volume * and SMC formats